### ISSUE TITLE
Menambahkan Deskripsi Cara Menjalankan Proyek

### ISSUE THREAD

**Issue by jefrydco** [fadhlisy/spa-vue-intermediate#1]
Hi, terima kasih telah mengirim submisi challenge Vue.js Intermediate. Saya sangat mengapresiasi kerja keras Mas Fadhli. Mas juga sudah menambahkan Tailwind CSS sebagai kerangka kerja gayanya dan secara tampilan juga sudah cukup responsif. Keren Mas! Menurut saya pengalaman pengguna bagian login dan register cukup menarik Mas. :smile: 

Mungkin dari saya ada sedikit saran terkait proyek yang Mas kirimkan, yakni menambahkan deskripsi cara menjalankan proyek di bagian `readme.md`.

Semangat selalu ya! :muscle:

**Comment by fadhlisy** [comment]
Terimakasih Mas Jefry atas masukannya. Saya sendiri juga baru dalam penggunaan github, belum terlalu mengerti. Untuk readme sudah saya update juga mas.
Sekali lagi terimakasih mas.
